# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c5212b96abd954ff3174704432448e21be9a8ed4ff76c769a497f5c1c71995ce0a52f57eda35331a470f37fe9e87efc60fa56f9d6a26dd41787c5933898251b

test:
  secret_key_base: f6fc2d2285804dc27bc8eb453d21c5b26c31e1363cfd517c879b883383f739b4f5e468ea0e43f58d5c0221b9b1cdb499cc2b346084b4bb81b405a62dd68e5f89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: uit974yriuevry29837rouwieving83ocuroivunb498pc2owrevisnu8948o3cwrinvt849vowrunvt89472ocwruivnt42983cwoeivntb789479832cwroeivunt4
